#!/usr/bin/env python3

import os
import random
import textwrap
import sys
  
if len(sys.argv) != 2 or (len(sys.argv) == 2 and sys.argv[1] == "--help"):
    help="""
       Shuffle all files in the directory passed as argument.
       Files are replaced by their shuffled versions (i.e. this
       is an in-place operation)
       
       Each file must fit in memory (one at a time).

       Usage: shuffle-files-in-directory "/path/to/my/dir"
       """
    print(textwrap.dedent(help))
    exit(1)

path = os.path.abspath(sys.argv[1])

for root, directories, filenames in os.walk(path):
    for directory in directories:
        # in python 3 print needs parens    
        print(os.path.join(root, directory))
    for filename in filenames:
        # in python 3 print needs parens

        full_path_to_file = os.path.join(root,filename)

        with open(full_path_to_file,'r') as f:
            data = [(random.random(), line) for line in f]

        os.remove(full_path_to_file)    
        data.sort()

        with open(full_path_to_file,'w') as f:    
            for _, line in data:
                f.write(line)
                

# print 'This script was passed', len(sys.argv), 'arguments.'
# print 'Arguments:', str(sys.argv)

# [[ "$source" != "" ]]

# for f in some/path/*; do
#   echo "$f"
# done 